# Generated by Django 2.1.15 on 2021-04-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vemoss', '0002_user_full_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
