# Generated by Django 2.1.15 on 2021-04-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vemoss', '0004_auto_20210406_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
