# Generated by Django 2.1.15 on 2021-04-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vemoss', '0005_auto_20210406_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
