# Generated by Django 2.0 on 2021-04-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vemoss', '0007_auto_20210406_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
